apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux.svc
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-poll-interval=5m
            - --sync-interval=5m
            - --git-branch=add-helm-release-support
            - --git-path=clusters/00-namespaces,clusters/beta
            - --git-url=git@github.com:ardikabs/kubernetes-flux-gitops

            # Include this if you want to restrict the manifests considered by flux
            # to those under the following relative paths in the git repository
            # - --git-label=flux-sync
            - --git-user=Satpam
            - --git-email=me@ardikabs.com

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 1Gi
