
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  template:
    spec:
      containers:
        - name: order
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 4
              memory: 4Gi
