apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      name: order
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/port: "3031" # tell prometheus to scrape /metrics endpoint's port.
      labels:
        name: order
    spec:
      containers:
        - name: order
          image: ardikabs/order:1.19.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
          - containerPort: 3030 # informational
          livenessProbe:
            httpGet:
              port: 3030
              path: /api/order/v6/identity.pub
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 3030
              path: /api/order/v6/identity.pub
            initialDelaySeconds: 5
            timeoutSeconds: 5
