apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: helm-operator
          args:
          - --enabled-helm-versions=v3
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1
              memory: 1Gi
