apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  values:
    ## nginx configuration
    ## Ref: https://github.com/kubernetes/ingress/blob/master/controllers/nginx/configuration.md
    ##
    controller:

      podPriorityClassName: ""

      # Configures the ports the nginx-controller listens on
      containerPort:
        http: 80
        https: 443

      dnsPolicy: ClusterFirst

      ## Election ID to use for status update
      ##
      electionID: ingress-controller-leader

      ## Name of the ingress class to route through this controller
      ##
      ingressClass: nginx

      # labels to add to the pod container metadata
      podLabels: {}

      ## Security Context policies for controller pods
      ##
      podSecurityContext: {}

      ## Node tolerations for server scheduling to nodes with taints
      ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
      ##
      tolerations: []

      ## Affinity and anti-affinity
      ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
      ##
      affinity: {}

      ## Node labels for controller pod assignment
      ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
      ##
      nodeSelector: {}

      ## Liveness and readiness probe values
      ## Ref: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes
      ##
      healthCheckPath: "/healthz"

      livenessProbe:
        failureThreshold: 5
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        port: 10254

      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        port: 10254

      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 11
        targetCPUUtilizationPercentage: 50
        targetMemoryUtilizationPercentage: 50

      # Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
      config: {}

      ## Annotations to be added to the controller config configuration configmap
      ##
      configAnnotations: {}

      # Will add custom headers before sending traffic to backends according to https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/customization/custom-headers
      proxySetHeaders: {}

      # Will add custom headers before sending response traffic to the client according to: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#add-headers
      addHeaders: {}

      # Optionally customize the pod dnsConfig.
      dnsConfig: {}

      ## Allows customization of the configmap / nginx-configmap namespace
      ##
      configMapNamespace: ""   # defaults to .Release.Namespace

      ## Allows customization of the tcp-services-configmap
      ##
      tcp:
        configMapNamespace: ""   # defaults to .Release.Namespace
        ## Annotations to be added to the tcp config configmap
        annotations: {}

      ## Allows customization of the udp-services-configmap
      ##
      udp:
        configMapNamespace: ""   # defaults to .Release.Namespace
        ## Annotations to be added to the udp config configmap
        annotations: {}
